config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount API::Base, at: '/'
  #mount GrapeSwaggerRails::Engine, at: "/documentation"
  root to:'questions#index'
  # root to: 'sessions#new'
  # devise_scope :user do
  #   get "/users/sign_in" => "sessions#new"
  # end

  resources :questions
  resource :comments, only: [:edit, :destroy]
  resources :users, only: [:edit, :update]
  resources :questions do
    resources :answers
  end

  post 'upvote_answer' => 'answers#upvote_answer'
  post 'downvote_answer' => 'answers#downvote_answer'
  post 'show_upvoted_users' => 'upvotedownvotes#show_upvoted_users'
  post 'show_comments_of_a_answer' => 'comments#show_comments_of_a_answer'
  post 'new_comment' => 'comments#new_comment'
  get 'all_answers_of_a_user' => 'users#all_answers_of_a_user'
  post 'change_profile_picture' => 'users#change_profile_picture'
  get 'all_questions_of_a_user' => 'users#all_questions_of_a_user'
  get 'all_followers_of_a_user' => 'users#all_followers_of_a_user'
  get 'all_following_of_a_user' => 'users#all_following_of_a_user'
  get 'follow_a_user' => 'users#follow_a_user'
  get 'unfollow_a_user' => 'users#unfollow_a_user'
  get 'next_page_in_question' => 'questions#next_page'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, :dependent => :destroy 
  attr_accessor :content

end

app/controllers/api/v1/questions.rb
module API
  module V1
    class Questions < Grape::API
      include API::V1::Defaults

      resource :questions do
        desc 'Return all questions'
        get '/all' do
          Question.all
        end
      end
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @all_questions = Question.paginate(page: params[:page], per_page: 6)
    @page_no = 1
    @last_answer_of_all_questions = {}
    @user_of_last_answer = {}
    @all_questions.each do |question|
      all_answers_for_current_question = question.answers
      unless all_answers_for_current_question.empty?
        last_answer = all_answers_for_current_question.last
        @last_answer_of_all_questions[question.id] = last_answer
        last_user = User.find_by_id(last_answer.user_id)
        @user_of_last_answer[question.id] = last_user
      end
    end
    # render json: { status: true, next_page: render_to_string('/questions/_questions',layout: false)}
    # respond_to :html, :js
  end

  def next_page
    @all_questions = Question.paginate(page: params[:page], per_page: 6)
    @last_answer_of_all_questions = {}
    @user_of_last_answer = {}
    @all_questions.each do |question|
      all_answers_for_current_question = question.answers
      unless all_answers_for_current_question.empty?
        last_answer = all_answers_for_current_question.last
        @last_answer_of_all_questions[question.id] = last_answer
        last_user = User.find_by_id(last_answer.user_id)
        @user_of_last_answer[question.id] = last_user
      end
    end
    if @all_questions.empty?
      render json: { status: false }
    else
      render json: { status: true, next_page: render_to_string('/questions/_questions', local: {all_questions: @all_questions,
                    last_answer_of_all_questions: @last_answer_of_all_questions, user_of_last_answer: @user_of_last_answer }, layout: false)}
     end
  end

  def new
    @question = Question.new
  end

  def create
    begin
      @question = current_user.questions.create!(question_params)
      current_user.questions_count += 1
      current_user.save!
      rescue
      @question = Question.new
      render 'new'
    end
    redirect_to  questions_path
  end

  def edit
    @question = Question.find_by(id: params[:id])
  end

  def update
    updated_q_string = params[:question][:name]
    question_id = params[:id]
    begin
      question = Question.find_by_id(question_id)
      question.update!(name: updated_q_string)
    rescue
      redirect_to edit_question_path
      return
    end
    redirect_to questions_path
  end

  def destroy
    begin
      @question = Question.find_by(params[:id])
      @question.answers.delete_all
      @question.delete
    rescue

    end

    redirect_to questions_path
  end

  private

  def question_params
    params.require(:question).permit(:name)
  end


end

app/views/questions/_questions.html.erb
 <% @all_questions.each do |question| %>
      <div id="onclick_hide-<%= question.id %>" class="question_answer">
        <div id="hide_question-<%= question.id %>" style="float: right; cursor: pointer; color: #aaa; ">X</div>
        <div class="question"><%= link_to question.name, question_answers_path(question), :class => 'question_link' %></div>
        <% if !@last_answer_of_all_questions[question.id].nil? %>

            <div id="removing_answer_after_deletion-<%= @last_answer_of_all_questions[question.id].id %>">
              <%= render 'common/user_details', user: @user_of_last_answer[question.id] %><br>
              <span id="updated_answer-<%= @last_answer_of_all_questions[question.id].id%>" ><%= render 'common/answer_details', answer: @last_answer_of_all_questions[question.id] %></span>
            </div>

            <div id="edit_box_and_update_button-<%= @last_answer_of_all_questions[question.id].id %>" class="edit_box_and_update_button_togather" style="display: none">
              <div> <input type="text" value="<%= @last_answer_of_all_questions[question.id].content %>" id="editing_answer_field-<%= @last_answer_of_all_questions[question.id].id%>"  class="update-answer"></div>
              <div> <input type="submit" value="update answer" id="update_answer_btn-<%= @last_answer_of_all_questions[question.id].id %>" class="btn-primary" style="float: right"></div>
            </div>
            <% if @user_of_last_answer[question.id].id  == current_user.id %>
                <div id="three_dot_menu-<%= @last_answer_of_all_questions[question.id].id %>" class="three-dot-menu">
                  <div class="dropup pull-left">
                    <div data-toggle="dropdown">...</div>
                    <ul class="dropdown-menu">
                      <li id="edit_answer-<%= @last_answer_of_all_questions[question.id].id %>"> Edit </li>
                      <li id="delete_answer-<%= @last_answer_of_all_questions[question.id].id %>"> Delete</li>
                    </ul>
                  </div>
                </div>
            <% end %>
         <% else %>
            <div style="margin-top: 16px">
              <input type="submit" value="Answer" id="submit_answer-<%= question.id %>" class= "submit-answer btn-primary">
              <div id="answer_a_question-<%= question.id %>", class= "answer_a_question" , style="display: none; margin-top: 16px; margin-left: -16px ">
                <div class="user_profile_in_question_menu" style="float: left; width: 600px">
                  <%= render 'users/user_profile_pic_small', user: current_user %>
                  <%= link_to current_user.name, all_answers_of_a_user_path(id: current_user.id) %>
                </div>
                <div style="float: left; width: 600px;">
                  <%= form_for Answer.new , url: question_answers_url(question) do |f| %>
                      <%= f.text_area :content , placeholder: 'Write your answer', class: 'answer_text_area' %></br>
                      <div class="submit_answer_in_question_menu" ><%= f.submit 'submit', :class => 'btn-primary ' %></div>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>
      </div>
  <% end %>
 <script>
     $('[id*="submit_answer-"]').click(function(e){
         e.preventDefault()
         var question_id = (this.id).substring('submit_answer-'.length)
         var id_for_input_of_a_answer = 'submit_answer-' + question_id
         var answer_a_question = 'answer_a_question-' + question_id
         $('#' + id_for_input_of_a_answer).hide()
         $('#' + answer_a_question).show()
     })

     $('[id*="hide_question-"]').click(function(e){
         e.preventDefault()
         var question_id = (this.id).substring('hide_question-'.length)
         var onclick_hide = 'onclick_hide-' + question_id
         $('#' + onclick_hide).hide()
//
     })

 </script>

app/views/questions/edit.html.erb
<div class="container">
  <%= form_for @question, url: question_path(@question), method: :put do |f| %>
      <%= f.text_area :name %></br>
      <%= f.submit %>
  <% end %>
</div>

app/views/questions/index.html.erb
<div class="content-wraper">
  <div class="ask_question">
    <%= link_to 'What is your question?', new_question_path %>
  </div>

  <% @all_questions.each do |question| %>
      <div id="onclick_hide-<%= question.id %>" class="question_answer">
        <div id="hide_question-<%= question.id %>" style="float: right; cursor: pointer; color: #aaa; ">X</div>
        <div class="question"><%= link_to question.name, question_answers_path(question), :class => 'question_link' %></div>
        <% if !@last_answer_of_all_questions[question.id].nil? %>

            <div id="removing_answer_after_deletion-<%= @last_answer_of_all_questions[question.id].id %>">
              <%= render 'common/user_details', user: @user_of_last_answer[question.id] %><br>
              <span id="updated_answer-<%= @last_answer_of_all_questions[question.id].id%>" ><%= render 'common/answer_details', answer: @last_answer_of_all_questions[question.id] %></span><br>
            </div>

            <div id="edit_box_and_update_button-<%= @last_answer_of_all_questions[question.id].id %>" class="edit_box_and_update_button_togather" style="display: none">
              <textarea style="width: 550px; height: 80px" name="comment" form="usrform" id="editing_answer_field-<%= @last_answer_of_all_questions[question.id].id%>"  class="update-answer" > <%= @last_answer_of_all_questions[question.id].content %></textarea>
              <div> <input type="submit" value="update answer" id="update_answer_btn-<%= @last_answer_of_all_questions[question.id].id %>" class="btn-primary" style="float: right; margin: 8px"></div>
            </div>

            <% if @user_of_last_answer[question.id].id  == current_user.id %>
                <div id="three_dot_menu-<%= @last_answer_of_all_questions[question.id].id %>" class="three-dot-menu">
                  <div class="dropup pull-left">
                    <div data-toggle="dropdown">...</div>
                    <ul class="dropdown-menu">
                      <li id="edit_answer-<%= @last_answer_of_all_questions[question.id].id %>" style="margin-left: 8px" > Edit </li>
                      <li id="delete_answer-<%= @last_answer_of_all_questions[question.id].id %>" style="margin-left: 8px"> Delete </li>
                    </ul>
                  </div>
                </div>
            <% end %>
        <% else %>
            <div style="margin-top: 16px">
              <input type="submit" value="Answer" id="submit_answer-<%= question.id %>" class= "submit-answer btn-primary">
              <div id="answer_a_question-<%= question.id %>", class= "answer_a_question" , style="display: none; margin-left: -16px ">
                <div class="user_profile_in_question_menu" style="float: left; width: 600px">
                  <%= render 'users/user_profile_pic_small', user: current_user %>
                  <%= link_to current_user.name, all_answers_of_a_user_path(id: current_user.id) %>
                </div>
                <div style="float: left; width: 600px;">
                  <%= form_for Answer.new , url: question_answers_url(question) do |f| %>
                      <%= f.text_area :content , placeholder: 'Write your answer', class: 'answer_text_area' %></br>
                      <div class="submit_answer_in_question_menu" ><%= f.submit 'submit', :class => 'btn-primary ' %></div>
                  <% end %>
                </div>
              </div>
            </div>
        <% end %>

      </div>
  <% end %>
  <div id="infinite-scrolling" >
  </div>
  <div class="loading" style="display: none">
       Loading . . .
  </div>
</div>

<script>

    var next_page = 1;
    $(window).scroll(function(e) {
        e.preventDefault()
       if (($(window).scrollTop() > $(document).height() - $(window).height() - 1) && next_page > 0 ){
           $('.loading').show()
           next_page = next_page + 1;
           $.ajax({
               url: '/next_page_in_question',
               type: 'get',
               datatype: 'json',
               data: {	"page": next_page},
               success: function(response){
                   if (response['status'] === true){
                       $('.loading').hide()
                     $('#infinite-scrolling').append(response['next_page'])
                   }else{
                       $('.loading').hide()
                       next_page = -1
                   }
               }
           }).error(function(){
               alert("something went wrong")
           })
       }
    })

    $('[id*="submit_answer-"]').click(function(e){
        e.preventDefault()
        var question_id = (this.id).substring('submit_answer-'.length)
        var id_for_input_of_a_answer = 'submit_answer-' + question_id
        var answer_a_question = 'answer_a_question-' + question_id
        $('#' + id_for_input_of_a_answer).hide()
        $('#' + answer_a_question).show()
    })

    $('[id*="edit_answer-"]').click(function(e){
        e.preventDefault()
        var answer_id = (this.id).substring('edit_answer-'.length)
        var updated_answer = 'updated_answer-' + answer_id
        $('#' + updated_answer).hide()
        var three_dot_menu = 'three_dot_menu-' + answer_id
        $('#' + three_dot_menu).hide()
        var edit_box_and_update_button = 'edit_box_and_update_button-' + answer_id
        $('#' + edit_box_and_update_button).show()
    })

    $('[id*="hide_question-"]').click(function(e){
        e.preventDefault()
        var question_id = (this.id).substring('hide_question-'.length)
        var onclick_hide = 'onclick_hide-' + question_id
        $('#' + onclick_hide).hide()
//
    })

    $('[id*="update_answer_btn-"]').click(function(e){
        e.preventDefault()
        var answer_id = (this.id).substring('update_answer_btn-'.length)
        var editing_answer_field_id = 'editing_answer_field-' + answer_id
        var updating_answer_field_text_value = $('#' + editing_answer_field_id).val()
        $.ajax({
            url: '/questions/:question_id/answers/:id/edit',
            type: 'get',
            datatype: 'json',
            data: {	"answer_id": answer_id, updating_answer_text: updating_answer_field_text_value },
            success: function(response){
                if (response['status'] === true){
                    var updated_answer = 'updated_answer-' + answer_id
                    $('#' + updated_answer).html(updating_answer_field_text_value)
                    $('#' + updated_answer).show()
                    var three_dot_menu = 'three_dot_menu-' + answer_id
                    $('#' + three_dot_menu).show()
                    var edit_box_and_update_button = 'edit_box_and_update_button-' + answer_id
                    $('#' + edit_box_and_update_button).hide()
                }
            }
        }).error(function(){
            alert("something went wrong")
        })
    })

    $('[id*="delete_answer-"]').click(function(e){
        e.preventDefault()
        var answer_id = (this.id).substring('delete_answer-'.length)
        $.ajax({
            url: '/questions/:question_id/answers/:id',
            type: 'delete',
            datatype: 'json',
            data: {	"answer_id": answer_id },
            success: function(response){
                if (response['status'] === true){
                    var removing_answer_field = 'removing_answer_after_deletion-' + answer_id
                    $('#' + removing_answer_field).remove()
                    var three_dot_menu = 'three_dot_menu-' + answer_id
                    $('#' + three_dot_menu).hide()
                }
            }
        }).error(function(){
            alert("something went wrong")
        })
    })


</script>

app/views/questions/new.html.erb
<div class="container">
  <%= form_for @question, url: '/questions' do |f| %>
      <%= f.text_area :name %></br>
      <%= f.submit %>
  <% end %>
</div>