config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount API::Base, at: '/'
  #mount GrapeSwaggerRails::Engine, at: "/documentation"
  root to:'questions#index'
  # root to: 'sessions#new'
  # devise_scope :user do
  #   get "/users/sign_in" => "sessions#new"
  # end

  resources :questions
  resource :comments, only: [:edit, :destroy]
  resources :users, only: [:edit, :update]
  resources :questions do
    resources :answers
  end

  post 'upvote_answer' => 'answers#upvote_answer'
  post 'downvote_answer' => 'answers#downvote_answer'
  post 'show_upvoted_users' => 'upvotedownvotes#show_upvoted_users'
  post 'show_comments_of_a_answer' => 'comments#show_comments_of_a_answer'
  post 'new_comment' => 'comments#new_comment'
  get 'all_answers_of_a_user' => 'users#all_answers_of_a_user'
  post 'change_profile_picture' => 'users#change_profile_picture'
  get 'all_questions_of_a_user' => 'users#all_questions_of_a_user'
  get 'all_followers_of_a_user' => 'users#all_followers_of_a_user'
  get 'all_following_of_a_user' => 'users#all_following_of_a_user'
  get 'follow_a_user' => 'users#follow_a_user'
  get 'unfollow_a_user' => 'users#unfollow_a_user'
  get 'next_page_in_question' => 'questions#next_page'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #mount_uploader :avatar, AvatarUploader
  has_many :questions, :dependent => :destroy
  has_many :answers, :dependent => :destroy
  has_many :upvote_downvotes, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :followers, :dependent => :destroy
end

app/controllers/api/v1/users.rb
module API
  module V1
    class Users < Grape::API
      include API::V1::Defaults

      resource :users do
        desc 'Return all users'
        get '/all' do
          User.all
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # attr_accessor :avatar
  # mount_uploader :avatar, AvatarUploader
  before_action :current_ability, only: [:edit, :update]

  # load_and_authorize_resource
  # skip_before_action :verify_authenticity_token

  def edit
    @active_user = current_user
  end

  def update
    @active_user = current_user
    @active_user.update!(permit_params)
    @active_user.avatar = params[:user][:avatar]
    @active_user.save!
    redirect_to questions_path
  end

  def all_answers_of_a_user
    @user = User.find_by_id!(params[:id])
    @r_u_following = @user.followers.where(following_id: current_user.id)
    @all_answers_by_user_with_questions = ActiveRecord::Base.connection.execute("SELECT questions.id as question_id, questions.name as question_name,
                                                  answers.content as answer_content, answers.upvate as upvote_count, answers.downvote as downvote_count, answers.id as answer_id,
                                                  answers.user_id as user_id_of_answer FROM questions INNER JOIN answers ON questions.id=answers.question_id WHERE answers.user_id=\'#{params[:id]}\'")
  end


  def change_profile_picture
    render json: {status: true}
  end

  def all_questions_of_a_user
    @user = User.find_by_id!(params[:user_id])
    @r_u_following = @user.followers.where(following_id: current_user.id)
    @all_questions = @user.questions.includes(:answers)
  end

  def all_followers_of_a_user
    begin
      # @r_u_following = Follower.find_by(follower_id: current_user.id, following_id: params[:user_id])
      @user = User.find_by_id!(params[:user_id])
      @r_u_following = @user.followers.where(following_id: current_user.id)
      @all_followers = @user.followers
    end
  end

  def all_following_of_a_user
    begin
      @user = User.find_by_id!(params[:user_id])
      @r_u_following = @user.followers.where('following_id =?', current_user.id)
      @all_followings = Follower.where(following_id: params[:user_id])
    end
  end

  def follow_a_user
    begin
      just_followed = User.find_by_id!(params[:following_id])
      k=just_followed.followers.create!(follower_name: current_user.name,following_id: current_user.id, following_name: just_followed.name)
      current_user.following_count += 1
      just_followed.followers_count += 1
      current_user.save!
      just_followed.save!
      render json: {status: true, follower_count: just_followed.followers_count}
    rescue Exception=>e
      Rails.logger.debug "exception --------#{e.message}----------"
      render json: {status: false, follower_count: just_followed.followers_count}
    end
  end

  def unfollow_a_user
    begin
      just_unfollowed = User.find_by_id!(params[:unfollowed_id])
      just_unfollowed.followers.where(following_id: current_user.id).first.delete
      current_user.following_count -= 1
      just_unfollowed.followers_count -= 1
      current_user.save!
      just_unfollowed.save!
      render json: {status: true, follower_count: just_unfollowed.followers_count}
    rescue Exception=>e
      Rails.logger.debug "exception --------#{e.message}----------"
      render json: {status: false, follower_count: just_unfollowed.followers_count}
    end

  end

  private

  def current_ability
    @ability = Ability.new(current_user)
  end

  def permit_params
    params.require(:user).permit(:name, :email, :phone)
  end
end

app/views/users/_about_a_follower.html.erb
<% if user.id == current_user.id %>
    <span  class="ur_followers">
      <span >Followers</span>
      <span>|</span>
      <span> <%= user.followers_count %></span>
     </span>
<% elsif r_u_following.empty? %>
    <span id="follow-<%= user.id %>" class="follow_btn">
      <span id="follow_text_in_follower_menu-<%= user.id %>">Follow</span>
      <span >|</span>
      <span id="follower_count_if_u_follow_in_follower_menu-<%= user.id %>"> <%= user.followers_count %></span>
    </span>

<% else %>
    <span id="unfollowed-<%= user.id %>" class="following_btn">
      <span id="following_text_in_follower_menu-<%= user.id %>">Following</span>
      <span >|</span>
      <span id="follower_count_if_u_unfollow_in_follower_menu-<%= user.id %>"> <%= user.followers_count %></span>
    </span>
<% end %>

app/views/users/_checking_for_follow_and_his_name.html.erb
<div class="follow_or_unfollow">
  <div>
    <%= user.name %>
  </div>
  <%= render 'follow_unfollow_a_user', user: user %>
</div>

app/views/users/_follow_unfollow_a_user.html.erb
<% if user.id == current_user.id %>
    <span  class="ur_followers">
      <span >Followers</span>
      <span>|</span>
      <span> <%= user.followers_count %></span>
     </span>
<% elsif @r_u_following.empty? %>
    <span id="follow_in_feed-<%= user.id %>" class="follow_btn">
      <span id="follow_text">Follow</span>
      <span>|</span>
      <span id="follower_count_if_u_followed_in_feed"> <%= user.followers_count %></span>
    </span>

<% else %>
    <span id="i_am_unfollowing_u-<%= user.id %>" class="following_btn">
      <span id="following_text">Following</span>
      <span >|</span>
      <span id="follower_count_if_u_unfollowed_in_feed"> <%= user.followers_count %></span>
    </span>

<% end %>

<script>
     $('[id*="i_am_unfollowing_u-"]').click(function(e){
         e.preventDefault()
         if(this.id.search('follow_in_feed-') >= 0){
             var following_id = (this.id).substring('follow_in_feed-'.length)
             $.ajax({
                 url: '/follow_a_user',
                 type: 'get',
                 datatype: 'json',
                 data: {	"following_id": following_id},
                 success: function(response){
                     if (response['status'] === true){

                         var older_span_id = 'follow_in_feed-' + following_id
                         var newer_span_id = 'i_am_unfollowing_u-' + following_id
                         var newer_class = 'following_btn'
                         $('#' + older_span_id).attr('id', newer_span_id);
                         $('#' + newer_span_id).attr('class', newer_class);
                         var older_follow_text = 'follow_text'
                         var newer_following_text = 'following_text'
                         $('#' + older_follow_text).attr('id',newer_following_text )
                         $('#' + newer_following_text).html('Following')
                         var older_follower_count_id = 'follower_count_if_u_followed_in_feed'
                         var newer_follower_count_id = 'follower_count_if_u_unfollowed_in_feed'
                         $('#' + older_follower_count_id).attr('id',newer_follower_count_id )
                         $('#' + newer_follower_count_id).html(response['follower_count'])
                         $('#follower_count_in_user_menu').html('Followers' + ' ' + response['follower_count'])

                     }
                 }
             }).error(function(){
                 alert("something went wrong")
             })
         }
         else {

             var unfollowed_id = (this.id).substring('i_am_unfollowing_u-'.length)
             $.ajax({
                 url: '/unfollow_a_user',
                 type: 'get',
                 datatype: 'json',
                 data: {	"unfollowed_id": unfollowed_id},
                 success: function(response){
                     if (response['status'] === true){

                         var older_span_id = 'i_am_unfollowing_u-' + unfollowed_id
                         var newer_span_id = 'follow_in_feed-' + unfollowed_id
                         var newer_class = 'follow_btn'
                         $('#' + older_span_id).attr('id', newer_span_id);
                         $('#' + newer_span_id).attr('class', newer_class);
                         var older_follow_text = 'following_text'
                         var newer_following_text = 'follow_text'
                         $('#' + older_follow_text).attr('id',newer_following_text )
                         $('#' + newer_following_text).html('Follow')
                         var older_follower_count_id = 'follower_count_if_u_unfollowed_in_feed'
                         var newer_follower_count_id = 'follower_count_if_u_followed_in_feed'
                         $('#' + older_follower_count_id).attr('id',newer_follower_count_id )
                         $('#' + newer_follower_count_id).html(response['follower_count'])
                         // $('#follower_count_if_u_unfollow').html(response['follower_count'])
                         $('#follower_count_in_user_menu').html('Followers' + ' ' + response['follower_count'])

                     }
                 }
             }).error(function(){
                 alert("something went wrong")
             })

         }

     })

     $('[id*="follow_in_feed-"]').click(function(e){
         e.preventDefault()
         if(this.id.search('follow_in_feed-') >= 0){
             var following_id = (this.id).substring('follow_in_feed-'.length)
             $.ajax({
                 url: '/follow_a_user',
                 type: 'get',
                 datatype: 'json',
                 data: {	"following_id": following_id},
                 success: function(response){
                     if (response['status'] === true){
                         var older_span_id = 'follow_in_feed-' + following_id
                         var newer_span_id = 'i_am_unfollowing_u-' + following_id
                         var newer_class = 'following_btn'
                         $('#' + older_span_id).attr('id', newer_span_id);
                         $('#' + newer_span_id).attr('class', newer_class);
                         var older_follow_text = 'follow_text'
                         var newer_following_text = 'following_text'
                         $('#' + older_follow_text).attr('id',newer_following_text )
                         $('#' + newer_following_text).html('Following')
                         var older_follower_count_id = 'follower_count_if_u_followed_in_feed'
                         var newer_follower_count_id = 'follower_count_if_u_unfollowed_in_feed'
                         $('#' + older_follower_count_id).attr('id',newer_follower_count_id )
                         $('#' + newer_follower_count_id).html(response['follower_count'])
                         $('#follower_count_in_user_menu').html('Followers' + ' ' + response['follower_count'])

                     }
                 }
             }).error(function(){
                 alert("something went wrong")
             })
         }
         else {

             var unfollowed_id = (this.id).substring('i_am_unfollowing_u-'.length)
             $.ajax({
                 url: '/unfollow_a_user',
                 type: 'get',
                 datatype: 'json',
                 data: {	"unfollowed_id": unfollowed_id},
                 success: function(response){
                     if (response['status'] === true){
                         var older_span_id = 'i_am_unfollowing_u-' + unfollowed_id
                         var newer_span_id = 'follow_in_feed-' + unfollowed_id
                         var newer_class = 'follow_btn'
                         $('#' + older_span_id).attr('id', newer_span_id);
                         $('#' + newer_span_id).attr('class', newer_class);
                         var older_follow_text = 'following_text'
                         var newer_following_text = 'follow_text'
                         $('#' + older_follow_text).attr('id',newer_following_text )
                         $('#' + newer_following_text).html('Follow')
                         var older_follower_count_id = 'follower_count_if_u_unfollowed_in_feed'
                         var newer_follower_count_id = 'follower_count_if_u_followed_in_feed'
                         $('#' + older_follower_count_id).attr('id',newer_follower_count_id )
                         $('#' + newer_follower_count_id).html(response['follower_count'])
                         $('#follower_count_in_user_menu').html('Followers' + ' ' + response['follower_count'])

                     }
                 }
             }).error(function(){
                 alert("something went wrong")
             })

         }

     })
</script>

app/views/users/_shared_feed_menu_with_profile.html.erb
<div class="user_profile">
  <div class="user_profile_pic"><%= render 'users/user_profile_pic' , user: user %></div>
  <div class="follow_or_unfollow"><%= render 'checking_for_follow_and_his_name', user: user %></div>
</div>

<div class="user_feed">
  <div class="feed_header">Feed</div>
  <div class="feed_menu">
    <div><%= link_to ( 'Answers' + '  ' + user.answers_count.to_s) , all_answers_of_a_user_path(id: @user.id) %></div>
    <div><%= link_to 'Questions' + ' ' + user.questions_count.to_s , all_questions_of_a_user_path(user_id: @user.id) %></div>
    <div><%= link_to 'Followers' + ' ' + user.followers_count.to_s, all_followers_of_a_user_path(user_id: @user.id) , id: 'follower_count_in_user_menu' %></div>
    <div><%= link_to 'Following' + ' ' + user.following_count.to_s, all_following_of_a_user_path(user_id: @user) %></div>
  </div>
</div>

app/views/users/_user_profile_pic.html.erb
<div>
  <% if user.avatar? %>
      <div > <%= image_tag(user.avatar_url) %></div>
  <% else %>
      <%= image_tag('profile.png')  %>
  <% end %>
</div>

app/views/users/_user_profile_pic_small.html.erb
<% if user.avatar? %>
    <div class='small_profile_pic'>
     <%= image_tag(user.avatar_url) %>
    </div>
<% else %>
    <div class="small_profile_pic">
     <%= image_tag('profile.png', class: 'small_profile_pic')  %>
    </div>
<% end %>

app/views/users/_user_profile_pic_uploader.html.erb
<div class="show_profile profile_wraper">
  <%= render 'user_profile_pic' , user: @active_user %>
  <div class="profile_updater">
    <%= f.file_field :avatar , class: 'choose_image' %>
    <div class="edit_profile_photo ">
      <a href="#">Edit Photo</a>
    </div>
    <%= f.hidden_field :avatar_cache %>
  </div>
</div>

app/views/users/all_answers_of_a_user.html.erb
<div class="content-wraper">
  <%= render 'shared_feed_menu_with_profile', user: @user %>
  <div class="user_feed_content">
  <div class="user_feed_content_count"> <%= @user.answers_count %> Answers</div>

  <% @all_answers_by_user_with_questions.each do |question_answer| %>
      <div class="question_answer">
        <div class="question"><%= link_to question_answer['question_name'], question_answers_path(question_answer['question_id']), :class => 'question_link' %></div>
          <div><%= render 'common/user_details', user: @user %></div>
          <div class="answer_content" style="margin-top: 40px" ><%= question_answer['answer_content'] %></div>
        <div class="upvote-count">
          <span id="upvoted_users_of_ans-<%= question_answer['answer_id']%>" > <%= link_to ('View' + ' ' + 'Upvoters') %> </span>
        </div>
        <div>
          <span id="upvote-<%= question_answer['answer_id'] %>" class="upvote-btn">
            <span >Upvote</span>
            <span>|</span>
            <span class="upvote-<%= question_answer['answer_id']%>"> <%= question_answer['upvote_count']  %></span>
          </span>
          <span id="downvote-<%= question_answer['answer_id'] %>" class="downvoted-btn">
            <span >Downvote</span>
            <span>|</span>
            <span class="downvote-<%= question_answer['answer_id'] %>"><%= question_answer['downvote_count'] %></span>
          </span>
        </div>
        <div id="upvoted_count_position_fixed-<%= question_answer['answer_id'] %>" style="display: none" class="upvoted_count_position_fixed" > <%= question_answer['upvote_count'] %>  Upvoters </div>
        <div id="upvoted_user_modal_wrapper-<%= question_answer['answer_id'] %>" class="upvoted_user_modal_wrapper" style="display: none">
          <div id="upvoted_answer_users-<%= question_answer['answer_id']%>" class="answer_voter_list">
          </div>
        </div>

        <div id="comment_box_and_comment_button-<%= question_answer['answer_id'] %>" class="comment-box-btn-togather" style="display: none">
          <div> <%= render 'users/user_profile_pic_small' , user: current_user %></div>
          <input type="text"  id="comment-answer-<%= question_answer['answer_id'] %>" placeholder="Add a comment...." class="add-comment">
          <input type="submit" value="Comment" id="submit-comment-<%= question_answer['answer_id'] %>" style="display: none" class="btn-primary">
        </div>
       <div  style="display: none"> <%= answer = Answer.find_by_id(question_answer['answer_id']) %></div>
        <% if (answer.comments.count > 0) %>
            <div id="load_comment_of_answer-<%= answer.id %>" class="all-comments">
              <%= render 'comments/load_comments', last_comment: answer.comments.last,user_of_last_comment: User.find_by_id(answer.comments.last.user_id), answer_id: answer.id %>
            </div>
        <% end %>
      </div>
  <% end %>
  </div>
</div>

<script>
    $(document).on('click', '.submit-answer', function(){
        $('.answer-a_question').show()
        $('.submit-answer').hide()

    })

    $('[id*="upvote-"]').click(function(){
        var answer_id = (this.id).substring('upvote-'.length)
        $.ajax({
            url: '/upvote_answer',
            type: 'post',
            datatype: 'json',
            data: {	"answer_id": answer_id},
            success: function(response){
                if (response['status'] === 1){
                    var upvote_count_class_name = "upvote-" + answer_id
                    var value_for_upvote_count = document.getElementsByClassName(upvote_count_class_name)[0].innerHTML
                    document.getElementsByClassName(upvote_count_class_name)[0].innerHTML = "" + (parseInt(value_for_upvote_count)+1)
                }
            }
        }).error(function(){
            alert("something went wrong")
        })
    });

    $('[id*="downvote-"]').click(function(){
        var answer_id = (this.id).substring('downvote-'.length)
        $.ajax({
            url: '/downvote_answer',
            type: 'post',
            datatype: 'json',
            data: {	"answer_id": answer_id},
            success: function(response){
                if (response['status'] === 1){
                    var upvote_count_class_name = "downvote-" + answer_id
                    var value_for_upvote_count = document.getElementsByClassName(upvote_count_class_name)[0].innerHTML
                    document.getElementsByClassName(upvote_count_class_name)[0].innerHTML = "" + (parseInt(value_for_upvote_count)+1)
                }
            }
        }).error(function(){
            alert("something went wrong")
        })
    })


    $('[id*="submit-comment-"]').click(function(){
        var answer_id = (this.id).substring('submit-comment-'.length)
        var  comment_id = 'comment-answer-' + answer_id
        var commented_text = document.getElementById(comment_id).value
        if(commented_text != ''){
            $.ajax({
                url: '/new_comment',
                type: 'post',
                datatype: 'json',
                data: {	"answer_id": answer_id, commented_text: commented_text},
                success: function(response){
                    if(response.status === true){
//                        var new_div = $('<div class="your_recent_comments"></div>')
//                        new_div.append(commented_text)
                        var comment_box_and_comment_button = 'comment_box_and_comment_button-' + answer_id
                        $('#' + comment_box_and_comment_button).after(response.recent_comment)
                        $('#' + comment_id).val('')
                    }
                }
            }).error(function(){
                alert("Invalid response")
            })
        }
    })

    $('[id*="comment-answer-"]').click(function(){
        var answer_id = (this.id).substring('comment-answer-'.length)
        var  comment_id = 'comment-answer-' + answer_id
        var submit_comment_btn_id = 'submit-comment-' + answer_id
        $('#' + submit_comment_btn_id).show()
    })


    $('[id*="comment_id-"]').click(function(e){
        e.preventDefault()
        var answer_id = (this.id).substring('comment_id-'.length)
        var comment_box_and_comment_button = 'comment_box_and_comment_button-' + answer_id
        $('#' + comment_box_and_comment_button).show()
        $('#' + comment_box_and_comment_button).show()
        var last_comment_id = 'comment_id-' + answer_id
        $('#' + last_comment_id).hide()
        $.ajax({
            url: '/show_comments_of_a_answer',
            type: 'post',
            datatype: 'json',
            data: {	"answer_id": answer_id},
            success: function(response){
                if (response['status'] === true){
                    var load_all_comment = 'load_all_comments-' + answer_id
                    $('#' + load_all_comment).html(response.all_comments_of_answer_partial_view);
                    $('#' + load_all_comment).show()

                }
            }
        }).error(function(){
            alert("something went wrong")
        })
    })

    $('[id*="upvoted_users_of_ans-"]').click(function(e){
        e.preventDefault()
        var answer_id = (this.id).substring('upvoted_users_of_ans-'.length)
        $.ajax({
            url: '/show_upvoted_users',
            type: 'post',
            datatype: 'json',
            data: {	"answer_id": answer_id},
            success: function(response){
                if (response['status'] === true){
                    var upvoted_answer_users_id = 'upvoted_answer_users-' + answer_id
                    var upvoted_user_modal_wrapper = 'upvoted_user_modal_wrapper-' + answer_id
                    var upvoted_count_position_fixed = 'upvoted_count_position_fixed-' + answer_id
                    $('#' + upvoted_count_position_fixed).attr('style', 'width: 582px !important');
                    $('#'+ upvoted_user_modal_wrapper).attr('style', 'width: 582px !important');
                    $('#' + upvoted_count_position_fixed).show()
                    $('#'+ upvoted_user_modal_wrapper).show()
                    $('#' + upvoted_answer_users_id).html(response.new_view_partial);
                }
            }
        }).error(function(){
            alert("something went wrong")
        })
    })

</script>

app/views/users/all_followers_of_a_user.html.erb
<%= render 'shared_feed_menu_with_profile', user: @user %>
<div class="user_feed_content">
  <div class="user_feed_content_count"> <%= @user.followers_count %> Followers</div>
</div>

<div class="all_follower">
  <% @all_followers.each do |follower| %>
      <div class="followers">
        <div class="user_profile_pic_in_follower">
          <%= render 'user_profile_pic_small', user: User.find_by_id(follower.following_id) %>
          <%= link_to follower.follower_name , all_answers_of_a_user_path(id: follower.following_id) %>
        </div>
        <div class="user_profile_pic_in_follower_space">

        </div>
        <div class="user_profile_pic_in_follower">
          <%= render 'about_a_follower', user: User.find_by_id(follower.following_id), r_u_following: User.find_by_id(follower.following_id).followers.where(following_id: current_user.id)%>
        </div>
      </div>
  <% end %>
</div>

app/views/users/all_following_of_a_user.html.erb
<%= render 'shared_feed_menu_with_profile', user: @user %>
<div class="user_feed_content">
  <div class="user_feed_content_count"> <%= @user.following_count %> Following</div>
</div>
<div class="all_following">
<% @all_followings.each do |following| %>
    <div class="followers">
      <div class="user_profile_pic_in_following">
        <%= render 'user_profile_pic_small', user: User.find_by_id(following.user_id) %>
        <%= link_to following.following_name , all_answers_of_a_user_path(id: following.user_id) %>
      </div>
      <div class="user_profile_pic_in_follower_space">

      </div>
      <div class="user_profile_pic_in_following">
        <%= render 'about_a_follower', user: User.find_by_id(following.user_id), r_u_following: User.find_by_id(following.user_id).followers.where(following_id: current_user.id)%>
      </div>
    </div>
<% end %>
</div>

app/views/users/all_questions_of_a_user.html.erb
<%= render 'shared_feed_menu_with_profile', user: @user %>
<div class="user_feed_content">
  <div class="user_feed_content_count"> <%= @user.questions_count %> Questions</div>
</div>

<div class="user_questions_in_menu">
  <% @all_questions.each do |question| %>
    <div class="question_answer_in_menu">
      <div class="question">
        <%= link_to question.name, question_answers_path(question) %><br>
      </div>
      <div class="answer_of_a_question_count_in_menu">
        <%= link_to (question.answers.count.to_s + ' ' + 'Answers'), question_answers_path(question) %>
        <%=' . ' + 'Asked ' + question.created_at.to_date.strftime('%b') + ' ' + question.created_at.to_date.strftime('%d') %>
      </div>
      <div>
        <input type="submit" value="Answer" id="submit_answer-<%= question.id %>" class= "submit-answer btn-primary">
        <div id="answer_a_question-<%= question.id %>", class= "answer_a_question" , style="display: none">
        <div class="user_profile_in_question_menu" style="float: left; width: 600px">
          <%= render 'users/user_profile_pic_small', user: current_user %>
          <%= link_to current_user.name, all_answers_of_a_user_path(id: current_user.id) %>
        </div>
        <div style="float: left; width: 600px;">
          <%= form_for Answer.new , url: question_answers_url(question) do |f| %>
              <%= f.text_area :content , placeholder: 'Write your answer', class: 'answer_text_area' %></br>
              <div class="submit_answer_in_question_menu" ><%= f.submit 'submit', :class => 'btn-primary ' %></div>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
    $('[id*="submit_answer-"]').click(function(e){
        e.preventDefault()
        var question_id = (this.id).substring('submit_answer-'.length)
        var id_for_input_of_a_answer = 'submit_answer-' + question_id
        var answer_a_question = 'answer_a_question-' + question_id
        $('#' + id_for_input_of_a_answer).hide()
        $('#' + answer_a_question).show()
    })
</script>

app/views/users/edit.html.erb
<div class="container">
    <%= form_for @active_user , url: user_path(current_user), html: { multipart: true }, method: :put do |f| %>
        <%= render 'user_profile_pic_uploader', f: f %>
        <div class="profile_wraper">
          <div><%= f.label :name, 'Name' %></div>
          <div><%= f.text_field :name %></br></div>
          <div> <%= f.label :email, 'Email Id' %></div>
          <%= f.text_field :email %></br>
          <div><%= f.label :phone, 'Phone No' %></div>
          <%= f.text_field :phone %></br>
          <%= f.submit %>
        </div>
    <% end %>
</div>

<script>
//  $('.choose_image').change(function(e){
////      $('.choose_image').val()
//      var data = new FormData(this)
//      e.preventDefault();
//      $.ajax({
//          url: '/change_profile_picture',
//          type: 'post',
//          datatype: 'json',
//          processData:false,
//          cache: false,
//          data: {	"image_data": data },
//          success: function(response){
//              if (response['status'] === 1){
//                  var upvote_count_class_name = "downvote-" + answer_id
//                  var value_for_upvote_count = document.getElementsByClassName(upvote_count_class_name)[0].innerHTML
//                  document.getElementsByClassName(upvote_count_class_name)[0].innerHTML = "" + (parseInt(value_for_upvote_count)+1)
//              }
//          }
//      }).error(function(){
//          alert("something went wrong")
//      })
//  })
</script>