config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount API::Base, at: '/'
  #mount GrapeSwaggerRails::Engine, at: "/documentation"
  root to:'questions#index'
  # root to: 'sessions#new'
  # devise_scope :user do
  #   get "/users/sign_in" => "sessions#new"
  # end

  resources :questions
  resource :comments, only: [:edit, :destroy]
  resources :users, only: [:edit, :update]
  resources :questions do
    resources :answers
  end

  post 'upvote_answer' => 'answers#upvote_answer'
  post 'downvote_answer' => 'answers#downvote_answer'
  post 'show_upvoted_users' => 'upvotedownvotes#show_upvoted_users'
  post 'show_comments_of_a_answer' => 'comments#show_comments_of_a_answer'
  post 'new_comment' => 'comments#new_comment'
  get 'all_answers_of_a_user' => 'users#all_answers_of_a_user'
  post 'change_profile_picture' => 'users#change_profile_picture'
  get 'all_questions_of_a_user' => 'users#all_questions_of_a_user'
  get 'all_followers_of_a_user' => 'users#all_followers_of_a_user'
  get 'all_following_of_a_user' => 'users#all_following_of_a_user'
  get 'follow_a_user' => 'users#follow_a_user'
  get 'unfollow_a_user' => 'users#unfollow_a_user'
  get 'next_page_in_question' => 'questions#next_page'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MiniQuora</title>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'main' %>
</head>
<body>
  <% if current_user %>
    <nav class="navbar navbar-light navbar-default SiteHeader">
      <div class="header-div">
        <div class="header-logo show-inline-header">
          <%= link_to 'MiniQuora',questions_path, :class => 'logo-link' %>
        </div>
        <div class="show-inline-header">
          <%= link_to 'Home',questions_path, :class => 'home-link' %>
        </div>
        <!--<div class="menu show-inline-header"><input class="form-control mr-sm-2" type="text" placeholder="Search"></div>-->
        <div class="dropdown profile show-inline-header">
          <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">About Me<span class="caret"></span></button>
          <ul class="dropdown-menu">
            <li> <%= link_to('Profile', edit_user_path(current_user)) if current_user %></li>
            <li><a href="#">Blogs</a></li>
            <li><a href="">Messages</a></li>
            <li><a href="#">Settings</a></li>
            <li class="divider"></li>
            <li> <%= link_to('Logout', destroy_user_session_path, method: :delete) if current_user %></li>
          </ul>
        </div>
      </div>
    </nav>
 <% end %>
  <%= yield %>
</body>
</html>